server:
  port: 8181
  compression:
    enabled: true
    mime-types: application/json,application/xml,application/javascript,text/html,text/xml,text/plain,text/javascript,text/css
    min-response-size: 2048 # Compress the response only if the response size is at least 2KB

spring:
  application:
    name: product project
  resources:
    cache:
       cachecontrol:
          max-age: 120 # Maximum time the response should be cached (in seconds)
          #The cache must re-validate stale resources with the server. Any expired resources must not be used without re-validating.
          must-revalidate: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: 123@Toor
    sql-script-encoding: utf-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  h2:
    console:
      enabled: true
